language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get install python-tk
#  - pip install .
# command to run tests
script: python2 run.py
